title: Soohyun Kwon
description: A personal blog about technology and life.
baseurl: "/my-awesome-blog" # Optional, if your site is in a subdirectory

theme: jekyll-theme-minimal

# Customize Theme Settings (Optional)
minimal:
  # Navigation
  nav:
    - title: Home
      url: /
    - title: About
      url: /about/
    - title: Blog
      url: /blog/

  # Footer
  footer:
    copyright: &copy; 2023 My Awesome Blog
